# Generated by Django 3.2.5 on 2021-10-20 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('subtitle', models.CharField(blank=True, max_length=50)),
                ('content', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=400, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('catagory', models.ForeignKey(default='Text', on_delete=django.db.models.deletion.CASCADE, to='base.catagory', to_field='title')),
            ],
        ),
        migrations.DeleteModel(
            name='TextPost',
        ),
    ]
