# Generated by Django 3.2.5 on 2021-10-20 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211020_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='catagory',
        ),
        migrations.DeleteModel(
            name='Catagory',
        ),
    ]
