# Generated by Django 3.2.5 on 2021-10-22 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_me'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='me',
            options={'verbose_name_plural': 'Me'},
        ),
        migrations.RenameField(
            model_name='me',
            old_name='what_am_i',
            new_name='what_i_do',
        ),
    ]
