# Generated by Django 3.2.5 on 2021-10-22 08:12

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20211022_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='me',
            name='since_when',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='Lorem ipsum dolor sit amet set, consectetur utes anet adipisicing elit, sed do eiusmod tempor incidist.', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='me',
            name='what_i_do',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='Lorem ipsum dolor sit amet set, consectetur utes anet adipisicing elit, sed do eiusmod tempor incidist.', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='me',
            name='who_am_i',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='Lorem ipsum dolor sit amet set, consectetur utes anet adipisicing elit, sed do eiusmod tempor incidist.', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='me',
            name='why_i_do_it',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='Lorem ipsum dolor sit amet set, consectetur utes anet adipisicing elit, sed do eiusmod tempor incidist.', max_length=5000, null=True),
        ),
    ]
