# Generated by Django 3.2.5 on 2021-10-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20211022_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='facebook_link',
            field=models.URLField(blank=True, default='https://facebook.com', null=True),
        ),
        migrations.AddField(
            model_name='me',
            name='instagram_link',
            field=models.URLField(blank=True, default='https://facebook.com', null=True),
        ),
        migrations.AddField(
            model_name='me',
            name='pinrest_link',
            field=models.URLField(blank=True, default='https://facebook.com', null=True),
        ),
        migrations.AddField(
            model_name='me',
            name='twitter_link',
            field=models.URLField(blank=True, default='https://facebook.com', null=True),
        ),
    ]
