# Generated by Django 3.2.5 on 2021-10-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20211022_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='me',
            name='instagram_link',
            field=models.URLField(blank=True, default='https://instagram.com', null=True),
        ),
        migrations.AlterField(
            model_name='me',
            name='pinrest_link',
            field=models.URLField(blank=True, default='https://pinterest.com', null=True),
        ),
        migrations.AlterField(
            model_name='me',
            name='twitter_link',
            field=models.URLField(blank=True, default='https://twitter.com', null=True),
        ),
    ]
