# Generated by Django 3.2.5 on 2021-10-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_post_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='me',
            name='since_when',
            field=models.TextField(blank=True, default='Lorem ipsum dolor sit amet set, consectetur utes anet adipisicing elit, sed do eiusmod tempor incidist.', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='me',
            name='what_i_do',
            field=models.TextField(blank=True, default='Lorem ipsum dolor sit amet set, consectetur utes anet adipisicing elit, sed do eiusmod tempor incidist.', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='me',
            name='who_am_i',
            field=models.TextField(blank=True, default='Lorem ipsum dolor sit amet set, consectetur utes anet adipisicing elit, sed do eiusmod tempor incidist.', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='me',
            name='why_i_do_it',
            field=models.TextField(blank=True, default='Lorem ipsum dolor sit amet set, consectetur utes anet adipisicing elit, sed do eiusmod tempor incidist.', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='/static/images/default.jpg', null=True, upload_to='images'),
        ),
    ]
